In [3]:
# Q1.Create a null vector of size 10 but the fifth value which is 1.

# Solution:
import numpy as np

array = np.zeros(10, dtype=int)
array[4] = 1
print(array)

[0 0 0 0 1 0 0 0 0 0]


In [30]:
# Q2.Create a vector with values ranging from 10 to 49.

#Solution:
array = np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# Q3. Create a 3x3 matrix with values ranging from 0 to 8

#Solution:
array = np.arange(9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
# Q4.Find indices of non-zero elements from [1,2,0,0,4,0]

#Solution:
array = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(array)
print("Indices of non-zero elements are: ",list(indices[0]))

Indices of non-zero elements are:  [0, 1, 4]


In [27]:
# Q5.Create a 10x10 array with random values and find the minimum and maximum values.

#Solution:
array = np.random.randint(100,size=(10, 10))
minimum = np.min(array)
maximum = np.max(array)

print(array)
print("Minimum value:", minimum)
print("Maximum value:", maximum)

[[37 41 31 40 92 84 68 16 20 30]
 [10 84 24 65 87  1 26 22 76 46]
 [76  0 11 46 41 18  4  0  5 43]
 [29 22 85 17 66  6 85 59 47 12]
 [46 23 51 33 32 22 89 79 58  3]
 [47 85 34 80 10 30 18 88 34 65]
 [87 52 36 47 29  6 78 15 76 38]
 [90 73 35 45 35 10 50 78 55 11]
 [51 91 47 32 55 74 53 11 50 97]
 [25 82 37 89 55 41 81 64 71 82]]
Minimum value: 0
Maximum value: 97


In [29]:
# Q6.Create a random vector of size 30 and find the mean value.

#Solution:
array = np.random.randint(100,size=(30))
Mean = np.mean(array)

print(array)
print("Mean value:", Mean)

[27 37 51 23 21 93 54  7 77 55 65 93 54 28 45  6 90 78 50 55 36  3  9 67
 71 58 17 95  6 13]
Mean value: 46.13333333333333
